# Generated by Django 2.0.7 on 2021-03-25 19:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('ie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcessoBagagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.TimeField(max_length=6)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(null=True)),
                ('item', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('hora_manifesto', models.TimeField(default=django.utils.timezone.now, max_length=6)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(default=django.utils.timezone.now)),
                ('data_final', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ENVIO', 'ENVIO'), ('EXCESSO DE BAGAGEM', 'EXCESSO DE BAGAGEM'), ('RECEBIMENTO', 'RECEBIMENTO'), ('GERAL', 'GERAL')], default='ENVIO', max_length=30)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='AÇAIEX')),
                ('hora_saida', models.TimeField(max_length=6)),
                ('responsavel_frete', models.CharField(choices=[('REMETENTE', 'REMETENTE'), ('DESTINATARIO', 'DESTINATARIO'), ('REDESPACHO', 'REDESPACHO')], default='REMETENTE', max_length=14, verbose_name='Resp. Frete')),
                ('data_venda', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('situacao_venda', models.CharField(choices=[('ATIVA', 'ATIVA'), ('CANCELADA', 'CANCELADA')], default='ATIVA', max_length=10, verbose_name='Situação')),
                ('tipo_frete', models.CharField(choices=[('PAGO', 'PAGO'), ('A PAGAR', 'A PAGAR'), ('CORTESIA', 'CORTESIA')], default='PAGO', max_length=10)),
                ('dinheiro', models.BooleanField()),
                ('cartao', models.BooleanField()),
                ('cartoes', models.CharField(blank=True, choices=[('DINNER CLUBS', 'DINNER CLUBS'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS'), ('CRED SHOP', 'CRED SHOP'), ('MASTER CARD', 'MASTER CARD'), ('VISA', 'VISA')], default='DINNER CLUBS', max_length=30, null=True)),
                ('ano_processo', models.CharField(blank=True, choices=[('DINNER CLUBS', 'DINNER CLUBS'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS'), ('CRED SHOP', 'CRED SHOP'), ('MASTER CARD', 'MASTER CARD'), ('VISA', 'VISA')], default='VISA', max_length=4, null=True)),
                ('valor_dinheiro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Dinheiro')),
                ('valor_cartao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Cartão')),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('cliente_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_destino', to='encom.Cliente')),
                ('cliente_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_origem', to='encom.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Empresa')),
                ('localidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_destino', to='encom.Localidade', verbose_name='Loc. Destino')),
                ('localidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_origem', to='encom.Localidade', verbose_name='Loc. Origem')),
                ('motorista_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorista_principal', to='encom.Motorista')),
                ('motorista_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_reserva', to='encom.Motorista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recebimento',
            name='venda',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='encom.Venda', verbose_name='venda'),
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='venda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Venda'),
        ),
        migrations.AddField(
            model_name='excessobagagem',
            name='intinerario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intinerario_destino', to='encom.Localidade', verbose_name='Intinerario. Destino'),
        ),
        migrations.AddField(
            model_name='excessobagagem',
            name='intinerario_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intinerario_origem', to='encom.Localidade', verbose_name='Intinerario. Origem'),
        ),
        migrations.AddField(
            model_name='excessobagagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencia',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Localidade'),
        ),
    ]
