# Generated by Django 2.1.5 on 2019-02-05 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('ie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.TimeField()),
                ('responsavel_frete', models.CharField(choices=[('REMETENTE', 'REMETENTE'), ('DESTINATARIO', 'DESTINATARIO'), ('REDESPACHO', 'REDESPACHO')], default='REMETENTE', max_length=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('situacao_venda', models.CharField(choices=[('ATIVA', 'ATIVA'), ('CANCELADA', 'CANCELADA')], default='ATIVA', max_length=10)),
                ('tipo_frete', models.CharField(choices=[('PAGO', 'PAGO'), ('A PAGAR', 'A PAGAR'), ('CORTESIA', 'CORTESIA')], default='PAGO', max_length=10)),
                ('dinheiro', models.BooleanField()),
                ('dinner_clubs', models.BooleanField()),
                ('american_express', models.BooleanField()),
                ('cred_shop', models.BooleanField()),
                ('master_card', models.BooleanField()),
                ('visa', models.BooleanField()),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Nota')),
                ('valor_dinheiro', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Dinheiro')),
                ('valor_cartao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Cartão')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('cliente_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_destino', to='encom.Cliente')),
                ('cliente_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_origem', to='encom.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Empresa')),
                ('localidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_destino', to='encom.Localidade')),
                ('localidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_origem', to='encom.Localidade')),
                ('motorista_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorista_principal', to='encom.Motorista')),
                ('motorista_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorista_reserva', to='encom.Motorista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agencia',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Localidade'),
        ),
    ]
