# Generated by Django 2.2.1 on 2021-07-29 01:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('encom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excessobagagem',
            name='data',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='ano_processo',
        ),
        migrations.AddField(
            model_name='excessobagagem',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='excessobagagem',
            name='data_excessobagagem',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='venda',
            name='a_prazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='prazos',
            field=models.CharField(blank=True, choices=[('30 DIAS', '30 DIAS'), ('60 DIAS', '60 DIAS'), ('90 SHOP', '90 DIAS')], default='30 DIAS', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_prazo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor a Prazo'),
        ),
    ]
