# Generated by Django 2.0.7 on 2021-03-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excessobagagem',
            old_name='data',
            new_name='data_excessobagagem',
        ),
    ]
