# Generated by Django 2.0.7 on 2021-03-28 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('encom', '0002_auto_20210325_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='excessobagagem',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='excessobagagem',
            name='data_excessobagagem',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
