# Generated by Django 2.2.1 on 2021-12-17 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encom', '0002_auto_20210728_2223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='carro',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='localidade',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='motorista',
            unique_together={('nome', 'cpf')},
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('nome',)},
        ),
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('hora_saida', 'responsavel_frete', 'empresa', 'localidade_origem', 'localidade_destino', 'carro', 'motorista_principal', 'motorista_reserva', 'data_venda', 'situacao_venda', 'tipo_frete', 'dinheiro', 'cartao', 'a_prazo', 'cartoes', 'prazos', 'valor_dinheiro', 'valor_cartao', 'valor_prazo', 'usuario', 'agencia')},
        ),
        migrations.CreateModel(
            name='Listagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISTA CLIENTES', 'LISTA CLIENTES')], default='LISTA CLIENTES', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
