# Generated by Django 2.1.5 on 2019-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0002_venda_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ManyToManyField(default=None, to='encom.Produto'),
        ),
    ]
