# Generated by Django 2.1.5 on 2019-02-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0003_auto_20190207_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.PositiveIntegerField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='encom.Produto')),
                ('venda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Venda')),
            ],
        ),
    ]
