# Generated by Django 3.0 on 2021-07-21 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0003_auto_20210327_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='ano_processo',
        ),
        migrations.AddField(
            model_name='venda',
            name='a_prazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='prazos',
            field=models.CharField(blank=True, choices=[('30 DIAS', '30 DIAS'), ('60 DIAS', '60 DIAS'), ('90 SHOP', '90 DIAS')], default='30 DIAS', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_prazo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor a Prazo'),
        ),
    ]
