# Generated by Django 2.2.1 on 2022-07-12 14:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0003_auto_20210327_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='conta_corrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_conta_corrente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Conta Corrente'),
        ),
    ]
