# Generated by Django 2.1.5 on 2019-02-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
    ]
