# Generated by Django 2.1.5 on 2019-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0005_remove_venda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Nota'),
        ),
    ]
