# Generated by Django 2.1.5 on 2019-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0008_auto_20190221_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
