# Generated by Django 2.1.7 on 2019-03-04 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0009_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data_final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_inicial',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
