# Generated by Django 2.1.7 on 2019-03-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0011_auto_20190305_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='hora_saida',
            field=models.TimeField(max_length=4),
        ),
    ]
