# Generated by Django 2.1.7 on 2019-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0012_auto_20190306_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
