# Generated by Django 2.1.7 on 2019-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0013_auto_20190307_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(decimal_places=9, max_digits=15, verbose_name='Valor Dinheiro'),
        ),
    ]
