# Generated by Django 2.1.7 on 2019-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0014_auto_20190307_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Dinheiro'),
        ),
    ]
