# Generated by Django 2.1.7 on 2019-03-08 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0015_auto_20190307_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data_final',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_inicial',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
