# Generated by Django 2.1.7 on 2019-03-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0016_auto_20190307_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True),
        ),
    ]
