# Generated by Django 2.1.7 on 2019-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0018_auto_20190308_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cartoes',
            field=models.CharField(blank=True, choices=[('DINNER CLUBS', 'DINNER CLUBS'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS'), ('CRED SHOP', 'CRED SHOP'), ('MASTER CARD', 'MASTER CARD'), ('VISA', 'VISA')], default='DINNER CLUBS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_cartao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Cartão'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Dinheiro'),
        ),
    ]
