# Generated by Django 2.1.7 on 2019-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0019_auto_20190311_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='hora_saida',
            field=models.TimeField(auto_now=True, max_length=4),
        ),
    ]
