# Generated by Django 2.1.7 on 2019-03-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0021_auto_20190312_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relatorio',
            new_name='RelatorioRomaneio',
        ),
    ]
