# Generated by Django 2.1.7 on 2019-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0023_auto_20190313_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_cartao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor Cartão'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor Dinheiro'),
        ),
    ]
