# Generated by Django 2.1.7 on 2019-03-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0024_auto_20190313_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='motorista_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_reserva', to='encom.Motorista'),
        ),
    ]
