# Generated by Django 2.1.7 on 2019-03-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0025_auto_20190313_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Produto'),
        ),
    ]
