# Generated by Django 2.1.7 on 2019-03-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0026_auto_20190313_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_nota',
        ),
    ]
