# Generated by Django 2.1.7 on 2019-03-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0028_venda_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='grupo',
            new_name='agencia',
        ),
    ]
