# Generated by Django 2.1.7 on 2019-03-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0029_auto_20190315_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='localidade_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_destino', to='encom.Localidade', verbose_name='Loc. Destino'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='localidade_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidade_origem', to='encom.Localidade', verbose_name='Loc. Origem'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='responsavel_frete',
            field=models.CharField(choices=[('REMETENTE', 'REMETENTE'), ('DESTINATARIO', 'DESTINATARIO'), ('REDESPACHO', 'REDESPACHO')], default='REMETENTE', max_length=14, verbose_name='Resp. Frete'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='situacao_venda',
            field=models.CharField(choices=[('ATIVA', 'ATIVA'), ('CANCELADA', 'CANCELADA')], default='ATIVA', max_length=10, verbose_name='Situação'),
        ),
    ]
