# Generated by Django 2.1.7 on 2019-03-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0031_venda_valor_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_nota',
        ),
    ]
