# Generated by Django 2.1.7 on 2019-03-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0035_auto_20190322_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento',
            name='venda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='encom.Venda', unique=True, verbose_name='venda'),
        ),
    ]
