# Generated by Django 2.1.7 on 2019-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0036_auto_20190322_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('ENVIO', 'ENVIO'), ('RECEBIMENTO', 'RECEBIMENTO')], default='ENVIO', max_length=30),
        ),
    ]
