# Generated by Django 2.1.7 on 2019-03-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0038_auto_20190322_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
