# Generated by Django 2.1.7 on 2019-03-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0039_auto_20190322_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='agencia',
        ),
    ]
