# Generated by Django 2.1.7 on 2019-03-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0042_auto_20190328_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
