# Generated by Django 2.1.7 on 2019-03-29 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0044_auto_20190329_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_cartao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Cartão'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Dinheiro'),
        ),
    ]
