# Generated by Django 2.1.7 on 2019-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0045_auto_20190329_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='hora_saida',
            field=models.TimeField(max_length=6),
        ),
    ]
