# Generated by Django 2.1.7 on 2019-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0046_auto_20190401_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='hora_saida',
            field=models.TimeField(max_length=6, verbose_name='Tempo'),
        ),
    ]
