# Generated by Django 2.1.7 on 2019-04-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0048_auto_20190402_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
