# Generated by Django 2.1.7 on 2019-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0049_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='venda',
            name='ano_processo',
            field=models.CharField(blank=True, choices=[('DINNER CLUBS', 'DINNER CLUBS'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS'), ('CRED SHOP', 'CRED SHOP'), ('MASTER CARD', 'MASTER CARD'), ('VISA', 'VISA')], default='VISA', max_length=4, null=True),
        ),
    ]
