# Generated by Django 2.1.5 on 2020-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0051_auto_20190419_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('ENVIO', 'ENVIO'), ('RECEBIMENTO', 'RECEBIMENTO'), ('GERAL', 'GERAL')], default='ENVIO', max_length=30),
        ),
    ]
