# Generated by Django 2.2.1 on 2020-08-18 14:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encom', '0052_auto_20200117_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcessoBagagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.TimeField(max_length=6)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(null=True)),
                ('item', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encom.Carro')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Empresa')),
                ('intinerario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intinerario_destino', to='encom.Localidade', verbose_name='Intinerario. Destino')),
                ('intinerario_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intinerario_origem', to='encom.Localidade', verbose_name='Intinerario. Origem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
