# Generated by Django 2.2.1 on 2020-08-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0053_excessobagagem_manifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='hora_manifesto',
            field=models.TimeField(auto_now=True, max_length=6),
        ),
    ]
