# Generated by Django 2.2.1 on 2020-07-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0053_excessobagagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='excessobagagem',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encom.Empresa'),
        ),
    ]
