# Generated by Django 2.2.1 on 2020-07-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0054_excessobagagem_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimento',
            name='agencia',
        ),
    ]
