# Generated by Django 2.2.1 on 2020-07-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('encom', '0055_remove_recebimento_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
