# Generated by Django 2.2.1 on 2020-07-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0056_recebimento_agencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recebimento',
            options={'ordering': ['-venda']},
        ),
    ]
