# Generated by Django 2.0.7 on 2020-11-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('encom', '0056_auto_20200818_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
