# Generated by Django 2.2.1 on 2020-07-28 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0058_auto_20200728_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
