# Generated by Django 2.2.1 on 2020-08-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0060_manifesto_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='venda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='encom.Venda'),
        ),
    ]
