# Generated by Django 2.2.1 on 2020-08-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0061_auto_20200805_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encom.Venda'),
        ),
    ]
