# Generated by Django 2.2.1 on 2020-08-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0062_auto_20200805_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifesto',
            name='venda',
        ),
    ]
