# Generated by Django 2.2.1 on 2020-08-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encom', '0064_manifesto_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifesto',
            name='venda',
        ),
    ]
